Fix NoClassDefFoundError exception on Storage Account node open in Azure Explorer
- Move 'dom4j' and 'jaxen' libraries dependency to idea since it is used for Java-related code. These libs intoduced an error on opening StorageAccount node in Azure Explorer